package tn.esprit.jdbc.entities;

public class User {
    private int userId;
 
    private int user_id; // Auto-generated by the database
 
    private String name;
    private String email;
    private String phone;
    private String password;
     private int admin; // 1 for admin, 0 for client

    // Constructors, getters, and setters
    public User() {}

    public User(String name, String email, String phone, String password, int admin) {
 
    // Default constructor (required for JavaBeans)
    public User() {
    }
    public User(String name, String email) {
        this.name = name;
        this.email = email;
    }

    // Parameterized constructor
    public User(String name, String email, String phone, String password) {
         this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
      this.admin = admin;
    }

    public User(int userId, String name, String email, String phone, String password, int admin) {
        this.userId = userId;
 
    }

    // Parameterized constructor
    public User(int user_id , String name, String email, String phone, String password) {
        this.user_id = user_id ;
 
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.admin = admin;

    }

    // Getters and Setters
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
        return user_id;
    }

    public void setUserId(int user_id) {
        this.user_id = user_id;
     }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getAdmin() {
        return admin;
    }

    public void setAdmin(int admin) {
        this.admin = admin;
    }

    @Override
    public String toString() {

        return "User{" +
                "userId=" + userId +
 
    @Override
    public String toString() {
        return "User{" +
                "user_id=" + user_id +
                 ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", password='" + password + '\'' +

                ", admin=" + admin +

                '}';
    }
}